library (ISLR)
Auto=read.table ("Auto.data", header =T,na.strings ="?")
names(Auto)
pairs(~ mpg + horsepower, Auto)
lm.fit =lm(mpg~horsepower ,data=Auto)
summary(lm.fit)
coef(lm.fit)
predict (lm.fit ,data.frame(horsepower=c(90,95,98,100) ), interval ="confidence")

ggplot(data = Auto, mapping = aes(x = horsepower, y = mpg)) + geom_point() + geom_smooth(method = "lm")
par(mfrow=c(2,2))
plot(lm.fit)
plot(Auto$horsepower ,Auto$mpg)
abline (lm.fit)
